# Phase 1: Tensor Foundations

Small examples for the completed tensor foundation features.

In [1]:
from babygrad.tensor import Tensor
from babygrad.types import NodeKind

## Tensor storage, shape, and indexing

A tensor stores values flat while its shape decides how indexing interprets those values.

In [2]:
scores = Tensor([1, 2, 3, 4, 5, 6], shape=(2, 3), kind=NodeKind.INPUT)

{
    "tensor": scores,
    "shape": scores.shape,
    "rank": scores.ndim,
    "items": scores.numel,
    "first_row": scores[0],
    "bottom_right": scores[-1, -1],
}

{'tensor': 2 rows x 3 cols
 [
   [1  2  3]
   [4  5  6]
 ],
 'shape': (2, 3),
 'rank': 2,
 'items': 6,
 'first_row': 3 items
 [1  2  3],
 'bottom_right': 6}

## Element-wise operations and broadcasting

Element-wise operations preserve the aligned shape. Bias-shaped tensors can broadcast across matrix rows.

In [3]:
features = Tensor([1, 2, 3, 4, 5, 6], shape=(2, 3), kind=NodeKind.INPUT)
row_bias = Tensor([10, 20, 30], shape=(1, 3), kind=NodeKind.INPUT)

shifted = features + row_bias
scaled = shifted * Tensor([2], shape=(1, 1), kind=NodeKind.INPUT)
rooted = Tensor([1, 4, 9, 16], shape=(2, 2), kind=NodeKind.INPUT).sqrt()
logged = Tensor([1, 10], shape=(1, 2), kind=NodeKind.INPUT).log()

{
    "shifted": shifted,
    "scaled": scaled,
    "sqrt": rooted,
    "log": logged,
}

{'shifted': 2 rows x 3 cols
 [
   [11  22  33]
   [14  25  36]
 ],
 'scaled': 2 rows x 3 cols
 [
   [22  44  66]
   [28  50  72]
 ],
 'sqrt': 2 rows x 2 cols
 [
   [1.0  2.0]
   [3.0  4.0]
 ],
 'log': 1 rows x 2 cols
 [
   [0.0  2.3026]
 ]}

## Reductions

Reductions keep rank by turning the reduced axis into size 1.

In [4]:
batch = Tensor([1, 2, 3, 4, 5, 6], shape=(2, 3), kind=NodeKind.INPUT)

{
    "column_totals": batch.sum(axis=0),
    "row_totals": batch.sum(axis=1),
    "last_axis_totals": batch.sum(axis=-1),
    "overall_mean": batch.mean(),
}

{'column_totals': 1 rows x 3 cols
 [
   [5  7  9]
 ],
 'row_totals': 2 rows x 1 cols
 [
   [ 6]
   [15]
 ],
 'last_axis_totals': 2 rows x 1 cols
 [
   [ 6]
   [15]
 ],
 'overall_mean': 1 rows x 1 cols
 [
   [3.5]
 ]}

## Shape manipulation

Reshape and flatten keep the values in row-major order. Transpose rearranges the 2D layout.

In [5]:
matrix = Tensor([1, 2, 3, 4, 5, 6], shape=(2, 3), kind=NodeKind.INPUT)

{
    "original": matrix,
    "reshaped": matrix.reshape((3, 2)),
    "flattened": matrix.flatten(),
    "transposed": matrix.transpose(),
}

{'original': 2 rows x 3 cols
 [
   [1  2  3]
   [4  5  6]
 ],
 'reshaped': 3 rows x 2 cols
 [
   [1  2]
   [3  4]
   [5  6]
 ],
 'flattened': 6 items
 [1  2  3  4  5  6],
 'transposed': 3 rows x 2 cols
 [
   [1  4]
   [2  5]
   [3  6]
 ]}

## Matrix multiplication

Matmul combines the left rows with the right columns.

In [6]:
left = Tensor([1, 2, 3, 4, 5, 6], shape=(2, 3), kind=NodeKind.INPUT)
right = Tensor([7, 8, 9, 10, 11, 12], shape=(3, 2), kind=NodeKind.INPUT)

left @ right

2 rows x 2 cols
[
  [ 58   64]
  [139  154]
]